### ISSUE TITLE
Screenshot Location? Screenshot Interval? Screenshot camera position?

### ISSUE THREAD

**Issue by TehFocus** [MrP123/TimeLapseMod#5]
Pretty much title.

We need more information on this mod. It sounds like a very interesting idea but as a user, such as myself, you basically have no clue what to do with it. The description of the mod does not tell us anything substantial.

It should be possible to change screenshot location in the options of the mod. It should be possible to change the interval of screenshots taken as well.

Also: From where does the mod take screenshots? Is it just taking a screenshot in my current position like pressing the screenshot key on steam or is it actually capable of taking a satellite-like image from the play area?

**Comment by MrP123** [comment]
There are a bunch of options for this mod, which can all be changed in the config.lua file.
The screenshots are saved in the script-output directory (\AppData\Roaming\Factorio\script-output) und the subdirectory TimeLapseMod.

The default screenshot interval is 5 min (300 s). 

The default camera position is the player position, but this can once again be canged in the config to take screenshots at a specified location (satellite-like image). This location can also be canged during play using a remote.call (once again see config.lua for more information)

I hope this answers your question(s).

I'll change the README in order to make this information more easily accessible, like it was when the mod was first release on the Factorio forums.
